## Практическая работа

В этой практической работе пять обязательных задач.

*Обязательные задачи* помогут проверить, что вы действительно усвоили материал модуля. Сдайте их на проверку.

Удачи!

Цели практической работы: 


1.   Потренироваться в обучении модели линейной регрессии.
2.   Потренироваться в обучении модели логистической регрессии. 
3.   Потренироваться в обучении модели многослойного персептрона.





Что оценивается:

*   Все пункты и критерии приёмки по каждому заданию выполнены.
*   Код оформлен и работает корректно.





Как отправить работу на проверку:

Сдайте практическую работу этого модуля через систему контроля версий Git сервиса Skillbox GitLab. После загрузки работы на проверку напишите об этом в личном кабинете своему куратору.

В этом задании вам нужно построить модель классификации, определяющую категорию цены/цену подержанного автомобиля в зависимости от характеристик транспортного средства. 

Мы будем использовать датасет из коллекции подержанных автомобилей, выставленных на продажу в Соединенных Штатах. Он уже подготовлен, без выбросов и с категориальными фичами, преобразованными с помощью one hot encoding, и количественными фичами, стандартизированными с помощью скейлеров.


### Описание датасета:
- `id`: идентификатор записи;
- `is_manufacturer_name`: признак производителя автомобиля;

- `region_*`: регион;
- `x0_*`: тип топлива;
- `manufacturer_*`: производитель;
- `short_model_*`: сокращённая модель автомобиля;
- `title_status_*`: статус;
- `transmission_*`: коробка передач;
- `state_*`: штат;
- `age_category_*`: возрастная категория автомобиля;

- `std_scaled_odometer`: количество пройденных миль (после стандартизации);
- `year_std`: год выпуска (после стандартизации);
- `lat_std`: широта (после стандартизации);
- `long_std`: долгота (после стандартизации);
- `odometer/price_std`: отношение стоимости к пробегу автомобиля (после стандартизации);
- `desc_len_std`: количество символов в тексте объявления о продаже (после стандартизации);
- `model_in_desc_std`: количество наименований модели автомобиля в тексте объявления о продаже (после стандартизации);
- `model_len_std`: длина наименования автомобиля (после стандартизации);
- `model_word_count_std`: количество слов в наименовании автомобиля (после стандартизации);
- `month_std`: номер месяца размещения объявления о продаже автомобиля (после стандартизации);
- `dayofweek_std`: день недели размещения объявления о продаже автомобиля (после стандартизации);
- `diff_years_std`: количество лет между годом производства автомобиля и годом размещения объявления о продаже автомобиля (после стандартизации);

- `price`: стоимость;
- `price_category`: категория цены.

## Обязательные задачи

In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

from sklearn.linear_model import LogisticRegression, LinearRegression
from sklearn.metrics import accuracy_score, confusion_matrix, mean_absolute_error, mean_squared_error
from sklearn.model_selection import train_test_split 
from sklearn.neural_network import MLPClassifier

In [2]:
df = pd.read_csv('data/vehicles_dataset_prepared.csv')
df.head()

id  price price_category  is_audi  is_ford  is_chevrolet  \
0  7308295377  54990           high        0        0             0   
1  7316380095  16942         medium        0        1             0   
2  7313733749  35590           high        0        0             0   
3  7308210929  14500         medium        0        0             0   
4  7303797340  14590         medium        0        0             0   

   is_toyota  x0_diesel  x0_electric  x0_gas  ...  long_std  year_std  \
0          0        1.0          0.0     0.0  ...  0.484245  1.322394   
1          0        0.0          0.0     0.0  ...  1.110800  0.695973   
2          0        0.0          0.0     1.0  ...  0.531185  0.852578   
3          1        0.0          0.0     1.0  ...  0.853562  0.226157   
4          0        0.0          0.0     0.0  ...  0.557607  0.069552   

   odometer/price_std  desc_len_std  model_in_desc_std  model_len_std  \
0           -0.510784      0.632075          -0.155788       1.163032   
1           -0.402947     -0.646781          -0.155788       0.932087   
2           -0.514480      0.560744          -0.155788       0.470197   
3           -0.241883      0.180435          -0.155788      -0.915473   
4           -0.333074      0.766366          -0.155788       1.163032   

   model_word_count_std  month_std  dayofweek_std  diff_years_std  
0              1.910669  -0.615846       1.120284       -1.322394  
1              1.235799   1.623784      -1.374972       -0.695973  
2              0.560930  -0.615846      -0.376870       -0.852578  
3             -0.788810  -0.615846       1.120284       -0.226157  
4              1.910669  -0.615846       0.122182       -0.069552  

[5 rows x 1463 columns]

**Задача 0. Линейная регрессия**

Вспомните задачу по предсказанию стоимости поддержанного автомобиля. Попробуем обучить модель линейной регрессии для предсказания цены автомобиля (колонка `price`). Для этого проделайте следующие шаги:

- Подготовьте данные: удалите колонки, которые косвенно содержат информацию о целевой переменной (`odometer/price_std`, `price_category`).
- Разделите выборку на треин и тест в отношении 70/30.
- Обучите модель линейной регрессии с дефолтными параметрами.
- Посчитайте значение метрики mae на тестовой выборке для линейной регрессии.
- Выведите получившиеся коэффициенты линейной регрессии при каждом параметре обучающей выборки с помощью метода `coef_`. Есть ли коэффициенты, которые равны нулю? Если есть, выведите названия фичей с нулевым коэффициентом
- Удалите фичи, коэффициенты которых равны нулю. И переобучите модель. Убедитесь, что значение метрики не изменилось.



In [3]:
# Ваш код здесь
df_prepared = df.copy()
df_prepared = df_prepared.drop(['odometer/price_std', 'price_category'], axis=1)

x = df_prepared.drop(['price'], axis=1)
y = df_prepared['price']

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

In [4]:
lin_model = LinearRegression()

In [5]:
lin_model.fit(x_train, y_train)

LinearRegression()

In [6]:
y_pred = lin_model.predict(x_test)

In [7]:
mean_absolute_error(y_test, y_pred)

4600.341115781948

In [8]:
np.mean(df['price'])

18014.65277055827

In [9]:
np.sqrt(mean_squared_error(y_test, y_pred))

6523.891399152556

In [10]:
lin_model.coef_

array([ 6.35951029e-06,  2.54302079e+02,  1.07390841e+03, ...,
       -1.66691604e+02,  2.30504356e+01, -2.80397999e+03])

In [11]:
coefficients = lin_model.coef_

for feature, coef in zip(x_train.columns, coefficients):
    print(feature, coef)

id 6.359510288389165e-06
is_audi 254.3020791961444
is_ford 1073.9084144091871
is_chevrolet -184.76442249460183
is_toyota 471.49878969127496
x0_diesel 5848.606938879127
x0_electric -2828.87006033968
x0_gas -1494.588263174715
x0_hybrid -780.5402163162712
x0_other -744.6076718639497
std_scaled_odometer -3529.6567549551883
short_model_-benz -5706.119254637908
short_model_1 -7089.737588611569
short_model_124 0.00038754808565499843
short_model_128i -8435.62494150644
short_model_135i -4437.962435544139
short_model_1500 -499.6192822908495
short_model_163869 301.88351831173776
short_model_1928 -0.00017087789683500887
short_model_1951 11515.894971750446
short_model_1954 2447.6969101197974
short_model_1960s -3561.681577165548
short_model_1966 41204.78814922692
short_model_1968 22801.394012073695
short_model_1972 11668.665063397488
short_model_1977 -0.00018445415662426967
short_model_1978 6010.053125043593
short_model_198.5 11293.534913425337
short_model_1988 -1178.420003698171
short_model_1994 -5

In [12]:
zero_coef_features = [feature for feature, coef in zip(x_train.columns, coefficients) if coef == 0]
if zero_coef_features:
    print(f'Фичи с нулевыми коэффициентами: {zero_coef_features}')
else:
    print('Нет фичей с нулевыми коэффициентами')

Фичи с нулевыми коэффициентами: ['manufacturer_ferrari']


In [13]:
df_prepared1 = df_prepared.drop(['manufacturer_ferrari'], axis=1)

In [14]:
x = df_prepared1.drop(['price'], axis=1)
y = df_prepared1['price']

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

In [15]:
lin_model1 = LinearRegression()
lin_model1.fit(x_train, y_train)

LinearRegression()

In [16]:
y_pred1 = lin_model1.predict(x_test)

In [17]:
mean_absolute_error(y_test, y_pred)

4600.341115781948

In [18]:
np.mean(df['price'])

18014.65277055827

В среднем модель справляется плохо. Нужно обработать данные для хороших результатов

**Задача 1. Логистическая регрессия**

Теперь в рамках тех же данных попробуйте предсказать `price_category` с помощью алгоритма логистической регрессии. Предварительно из датафрейма удалите переменные, в которых косвенно содержится информация о целевой переменной (`odometer/price_std`, `price`). 

Для обученной модели нужно:

- рассчитать и вывести метрику качества (accuracy) на тренировочной выборке;
- сделать предикт на тестовых данных и положить его в переменную `logreg_pred`;
- рассчитать и вывести accuracy и confusion_matrix на тестовой выборке.


Задание засчитывается, если: 
- accuracy на тренировочной выборке > 87%;
- accuracy на тестовой выборке > 75.5%.

Для улучшения метрики можно преобразовывать входные данные, тюнить параметры логистической регрессии.

In [19]:
# Ваш код подготовки данных здесь. Допишите инициализацию входных фичей и целевую переменную
df_prepared1 = df.copy()
df_prepared1 = df_prepared1.drop(['price', 'odometer/price_std', 'id'], axis=1)

x = df_prepared1.drop(['price_category'], axis=1)
y = df_prepared1['price_category']

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

In [20]:
# Ваш код обучения моделей здесь
logreg = LogisticRegression()
logreg.fit(x_train, y_train)

D:\conda\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [21]:
logreg_pred = logreg.predict(x_test)

In [22]:
accuracy_score(y_test, logreg_pred)

0.7543312543312544

In [23]:
confusion_matrix(y_test, logreg_pred)

array([[801,  26, 170],
       [ 22, 767, 164],
       [156, 171, 609]], dtype=int64)

In [24]:
logreg.get_params()

{'C': 1.0,
 'class_weight': None,
 'dual': False,
 'fit_intercept': True,
 'intercept_scaling': 1,
 'l1_ratio': None,
 'max_iter': 100,
 'multi_class': 'auto',
 'n_jobs': None,
 'penalty': 'l2',
 'random_state': None,
 'solver': 'lbfgs',
 'tol': 0.0001,
 'verbose': 0,
 'warm_start': False}

In [25]:
from sklearn.model_selection import GridSearchCV

In [26]:
param_grid = { 'C': [0.001, 0.01, 0.1, 1, 10],
              'solver': ['lbfgs', 'liblinear', 'newton-cg'],
              'penalty': ['l1', 'l2'],
              'max_iter': [50, 100, 200],
              'class_weight': [None, 'balanced']}

In [27]:
model1 = LogisticRegression(max_iter=1000)
grid_search1 = GridSearchCV(model1, param_grid, scoring='accuracy', cv=5)

In [28]:
grid_search1.fit(x_train, y_train)

D:\conda\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
D:\conda\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
D:\c

D:\conda\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
D:\conda\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
D:\c

D:\conda\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
D:\conda\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
D:\c

D:\conda\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
D:\conda\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
D:\c

D:\conda\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
D:\conda\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
D:\c

D:\conda\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


GridSearchCV(cv=5, estimator=LogisticRegression(max_iter=1000),
             param_grid={'C': [0.001, 0.01, 0.1, 1, 10],
                         'class_weight': [None, 'balanced'],
                         'max_iter': [50, 100, 200], 'penalty': ['l1', 'l2'],
                         'solver': ['lbfgs', 'liblinear', 'newton-cg']},
             scoring='accuracy')

In [29]:
grid_search_pred1 = grid_search1.predict(x_test)

In [30]:
accuracy_score(y_test, grid_search_pred1)

0.7550242550242551

In [31]:
confusion_matrix(y_test, grid_search_pred1)

array([[807,  25, 165],
       [ 22, 769, 162],
       [162, 171, 603]], dtype=int64)

In [32]:
grid_search1.best_params_

{'C': 1,
 'class_weight': 'balanced',
 'max_iter': 100,
 'penalty': 'l2',
 'solver': 'lbfgs'}

In [33]:
logreg_final = LogisticRegression(max_iter=1000, penalty='l1', solver = 'liblinear')

In [34]:
logreg_final.fit(x_train, y_train)

LogisticRegression(max_iter=1000, penalty='l1', solver='liblinear')

In [35]:
logreg_final_pred = logreg_final.predict(x_test)

In [36]:
accuracy_score(y_test, logreg_final_pred)

0.7574497574497574

In [37]:
confusion_matrix(y_test, logreg_final_pred)

array([[847,  34, 116],
       [ 28, 814, 111],
       [192, 219, 525]], dtype=int64)

От логистической регрессии выжать больше будет сложно в этой задаче. Как минимум нужно будет все данные перебрать снова. А это легче сделать на изначальных данных

**Задача 2. Многослойный персептрон**

Решите задачу, поставленную в предыдущем задании, применив модель многослойного персептрона. Добейтесь лучших значений точности на тренировочной и тестовой выборках, чем на логистической регрессии, с помощью данного алгоритма. 

Значимым увеличением точности в данном задании будем считать увеличение больше, чем на 0.01 по метрике accuracy.

In [38]:
# Ваш код здесь
mlp = MLPClassifier(random_state=42, max_iter=1000, hidden_layer_sizes=(100,30), activation='tanh')

In [39]:
mlp.fit(x_train, y_train)

MLPClassifier(activation='tanh', hidden_layer_sizes=(100, 30), max_iter=1000,
              random_state=42)

In [40]:
mlp_pred = mlp.predict(x_test)

In [41]:
accuracy_score(y_test, mlp_pred)

0.7623007623007623

In [42]:
confusion_matrix(y_test, mlp_pred)

array([[788,  27, 182],
       [ 16, 752, 185],
       [113, 163, 660]], dtype=int64)

In [43]:
from sklearn.preprocessing import StandardScaler
scalerr = StandardScaler()
scaled_X_train = scalerr.fit_transform(x_train)
scaled_X_testt = scalerr.transform(x_test)

In [44]:
mlp_8 = MLPClassifier(random_state=42, max_iter=1000, 
                      hidden_layer_sizes=(100,50), activation='relu', 
                      alpha=0.1,
                      learning_rate_init=0.001, batch_size=64,
                      solver='adam')

In [45]:
mlp_8.fit(scaled_X_train, y_train)

MLPClassifier(alpha=0.1, batch_size=64, hidden_layer_sizes=(100, 50),
              max_iter=1000, random_state=42)

In [46]:
mlp_8_pred = mlp_8.predict(scaled_X_testt)

In [47]:
accuracy_score(y_test, mlp_8_pred)

0.7633402633402634

In [48]:
confusion_matrix(y_test, mlp_8_pred)

array([[784,  31, 182],
       [ 15, 762, 176],
       [124, 155, 657]], dtype=int64)

**Задача 3. Сравнение с древовидными моделями**

Обучите модель случайного леса на тех же данных для предсказания `price_category`. Сравните качество с моделью логистической регрессии и многослойного персептрона. Словами опишите, какая из моделей в каких случаях работает лучше по результатам на тестовой выборке, и обоснуйте свой выбор.

In [49]:
# Ваш код здесь
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators=1200,
                             min_samples_split=2,
                             min_samples_leaf=1,
                             max_features='log2')

In [50]:
rfc.fit(scaled_X_train, y_train)

RandomForestClassifier(max_features='log2', n_estimators=1200)

In [51]:
rfc_pred = rfc.predict(scaled_X_testt)

In [52]:
accuracy_score(y_test, rfc_pred)

0.7605682605682605

In [53]:
confusion_matrix(y_test, rfc_pred)

array([[801,  42, 154],
       [ 13, 815, 125],
       [142, 215, 579]], dtype=int64)

Логистическая регрессия сама по себе старая модель который подходит не ко всем данным, тогда как нейронные сети и деревья очень сильные модели но требующие огромных ресурсов.

**Задача 4. Стратегия голосования**

Реализуйте стратегию голосования для предсказания целевой переменной.
Голосование в задаче классификации — это когда несколько моделей выдают свои предикты, и финальным выбирается тот предикт, который предсказали большинство моделей.

Для реализации этой стратегии проделайте следующее:

- сохраните предсказания каждой из моделей (случайный лес, многослойный персептрон, логистическая регрессия) для тестовой выборки в датафрейм `pred_df`;
- в четвертую колонку `target` положите тот класс, который предсказало большинство классификаторов. Например, если в строке были значения `high, medium, medium`, в `target` нужно положить `medium`.

     Если в строке три разных класса — `high, medium, low`, — придумайте свою стратегию по выбору значения. Самая простая стратегия: выбрать рандомно одно значение из трёх.

- посчитайте точность предсказания с помощью голосования. Выведите значения метрик accuracy и confusion_matrix.


Добейтесь значения точности > 78% 

In [54]:
# Ваш код здесь
pred_df = pd.DataFrame({
    'RandomForest': rfc_pred,
    'MLP': mlp_8_pred,
    'LogisticRegression': logreg_final_pred
})

In [55]:
def majority_vote(row):
    unique_classes = row.unique()
    if len(unique_classes) == 1:
        return unique_classes[0]
    else:
        return row.mode().iloc[0]

In [56]:
pred_df['target'] = pred_df.apply(majority_vote, axis=1)

In [57]:
voting_accuracy = accuracy_score(y_test, pred_df['target'])
conf_matrix = confusion_matrix(y_test, pred_df['target'])

print("Accuracy:", voting_accuracy)
print("Confusion Matrix:")
print(conf_matrix)

Accuracy: 0.7803187803187803
Confusion Matrix:
[[837  28 132]
 [ 28 814 111]
 [154 181 601]]


**Примечание:**

В этом домашнем задании в задаче номер 1 и далее перед вами встал выбор: включать ли в обучение колонку `id`. При удалении данной колонки во время обучении логистической регрессии качество заметно улучшается.

Вообще обучать любую модель (будь то логистическая или линейная регрессия, или древовидный алгоритм) на данных айдишников не считается хорошей практикой. Как правило, между `id` и целевой переменной не должно быть никаких взаимосвязей. Включая колонку `id` в качества атрибута в обучение, вы стараетесь "заточить" результаты своей модели под айдишники записей. Таким образом модель обучится на некотором наборе "частных случаев", и, возможно, не обратит внимание на общие зависимости.   